# Generated by Django 5.1.6 on 2025-02-15 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoitem',
            old_name='creates',
            new_name='created',
        ),
    ]
